# Generated by Django 3.0.5 on 2020-04-19 14:33

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ("accounts", "0002_auto_20200419_1433")]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "spending_limit",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="Spending limit on budget"),
                ),
                (
                    "spending_limit_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Day"), (2, "Week"), (3, "Month")],
                        null=True,
                        verbose_name="Spending Limit Type",
                    ),
                ),
                (
                    "family",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="budget", to="accounts.Family"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                (
                    "spending_limit_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "Day"), (2, "Week"), (3, "Month")],
                        null=True,
                        verbose_name="Spending Limit Type",
                    ),
                ),
                ("is_income_category", models.BooleanField()),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="categories", to="budget.Budget"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Categories", "unique_together": {("name", "budget")}},
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
                ("value", models.PositiveIntegerField()),
                ("title", models.CharField(default="", max_length=24)),
                ("note", models.TextField(blank=True, null=True)),
                ("is_income", models.BooleanField()),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="budget.Budget"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lines",
                        to="budget.Category",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
