# Generated by Django 3.0.5 on 2020-04-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("budget", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="category",
            name="spending_limit",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Spending limit on category"),
        )
    ]
