# Generated by Django 3.0.5 on 2020-04-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("accounts", "0002_auto_20200419_1433")]

    operations = [
        migrations.AlterModelOptions(
            name="family", options={"verbose_name": "Family", "verbose_name_plural": "Families"}
        )
    ]
